COPY INTO 's3://ivekorea-airflow-practice-taeeunk/clean_data/IVE_ANALYTICS_DATA'
FROM IVE_DATA.CLEAN.IVE_ANALYTICS_DATA
STORAGE_INTEGRATION = s3_int_taeeun
FILE_FORMAT = (TYPE = CSV)
HEADER = TRUE
SINGLE = FALSE
OVERWRITE = TRUE;