name: 'ive_dbt_project'
version: '1.0.0'
config-version: 2

profile: 'ive_dbt_profile'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

models:
  ive_dbt_project:
    +materialized: table
    
    clean:
      +schema: CLEAN