SELECT
    ADS_IDX AS "KEY", SCH_IDX AS "SCH_KEY",
    SCH_TYPE AS "RPT_TYPE", COALESCE(MDA_IDX_ARR, 'ALL') AS "MDA_ARR",
    CASE
        WHEN SCH_CLK_NUM >= 99999999 THEN 100000
        ELSE SCH_CLK_NUM END AS "TURN_GOAL",
    SCH_TURN_NUM AS "TURN_REAL"
FROM {{source('s3_raw_data', 'IVE_SCH_RAW')}}
WHERE
    SCH_CLK_NUM IS NOT NULL
    AND SCH_TURN_NUM IS NOT NULL
    AND SCH_CLK_NUM <> 9999999