SELECT
    ADS_IDX AS "KEY", MDA_IDX AS "MDA",
    RPT_TIME_DATE AS "DATE", RPT_TIME_TIME AS "TIME",
    RPT_TIME_CLK AS "TIME_CLK", RPT_TIME_TURN AS "TIME_TURN",
    RPT_TIME_ACOST AS "ADV_COST", RPT_TIME_COST AS "REWARD_COST", RPT_TIME_EARN AS "MDA_COST",
    ROUND(RPT_TIME_TURN/NULLIF(RPT_TIME_CLK,0)*100,2) AS "CVR",
    ROUND(RPT_TIME_TURN/NULLIF(RPT_TIME_ACOST,0)*1000,4) AS "1000_W_EFFICIENCY"
FROM {{source('s3_raw_data', 'IVE_YEAR_RAW')}}
WHERE
    RPT_TIME_CLK IS NOT NULL
    AND RPT_TIME_TURN IS NOT NULL
    AND RPT_TIME_CLK >= RPT_TIME_TURN
    AND RPT_TIME_ACOST >= RPT_TIME_EARN