COPY INTO 's3://ivekorea-airflow-practice-taeeunk/clean_data/IVE_ANALYTICS_DATA.csv'
FROM IVE_DATA.CLEAN.IVE_ANALYTICS_DATA
STORAGE_INTEGRATION = s3_int_taeeun
FILE_FORMAT = (
    TYPE = CSV
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    COMPRESSION = NONE
    NULL_IF = ('\\N')
    EMPTY_FIELD_AS_NULL = False
)
HEADER = TRUE
SINGLE = TRUE
MAX_FILE_SIZE = 5368709120
OVERWRITE = TRUE;