CREATE OR REPLACE TABLE IVE_DATA.CLEAN.IVE_ANALYTICS_DATA AS
SELECT
    Y."KEY", Y."DATE", Y."TIME", Y."MDA", Y."TIME_CLK", Y."TIME_TURN",
    Y."ADV_COST", Y."REWARD_COST", Y."MDA_COST", Y."CVR", Y."1000_W_EFFICIENCY",
    L."SCH_KEY", L."NAME", L."SAVE_WAY", L."GUIDE", L."OS_TYPE", L."REJOIN_TYPE",
    L."CONTRACT_PRICE", L."START_DATE", L."END_DATE", L."START_QUARTER", L."START_TIME",
    S."RPT_TYPE", S."MDA_ARR", S."TURN_GOAL", S."TURN_REAL"
FROM IVE_DATA.CLEAN.IVE_YEAR_CLEAN AS Y
LEFT JOIN IVE_DATA.CLEAN.IVE_LIST_CLEAN AS L ON Y."KEY"=L."KEY"
LEFT JOIN IVE_DATA.CLEAN.IVE_SCH_CLEAN AS S ON L."SCH_KEY"=S."SCH_KEY"
ORDER BY Y."DATE" DESC, Y."TIME" DESC;