CREATE SCHEMA IF NOT EXISTS IVE_DATA.CLEAN;

CREATE OR REPLACE TABLE IVE_DATA.CLEAN.IVE_SCH_CLEAN AS
SELECT
    ADS_IDX AS "KEY", SCH_IDX AS "SCH_KEY",
    SCH_TYPE AS "RPT_TYPE", COALESCE(MDA_IDX_ARR, 'ALL') AS "MDA_ARR",
    CASE
        WHEN SCH_CLK_NUM >= 99999999 THEN 100000
        ELSE SCH_CLK_NUM END AS "TURN_GOAL",
    SCH_TURN_NUM AS "TURN_REAL"
FROM IVE_DATA.RAW_DATA.IVE_SCH_RAW
WHERE
    SCH_CLK_NUM IS NOT NULL
    AND SCH_TURN_NUM IS NOT NULL
    AND SCH_CLK_NUM <> 9999999