CREATE SCHEMA IF NOT EXISTS IVE_DATA.CLEAN;

CREATE OR REPLACE TABLE IVE_DATA.CLEAN.IVE_LIST_CLEAN AS
SELECT
    ADS_IDX AS "KEY", SCH_IDX AS "SCH_KEY",
    ADS_NAME AS "NAME", ADS_SAVE_WAY AS "SAVE_WAY", ADS_SUMMARY AS "GUIDE",
    CASE
        WHEN ADS_OS_TYPE IN (2, 3, 8) THEN 'ANDROID'
        WHEN ADS_OS_TYPE = 1 THEN 'IOS'
        WHEN ADS_OS_TYPE = 7 THEN 'WEB'
        ELSE 'UNKNOWN' END AS "OS_TYPE"
    , ADS_REJOIN_TYPE AS "REJOIN_TYPE",
    ADS_CONTRACT_PRICE AS "CONTRACT_PRICE", ADS_SDATE AS "START_DATE", ADS_EDATE AS "END_DATE",
    CASE
        WHEN MONTH(ADS_SDATE) BETWEEN 1 AND 3 THEN '1Q'
        WHEN MONTH(ADS_SDATE) BETWEEN 4 AND 6 THEN '2Q'
        WHEN MONTH(ADS_SDATE) BETWEEN 7 AND 9 THEN '3Q'
        ELSE '4Q' END AS "START_QUARTER",
    CASE
        WHEN HOUR(ADS_SDATE) BETWEEN 0 AND 5 THEN 'EARLY MORNING'
        WHEN HOUR(ADS_SDATE) BETWEEN 6 AND 11 THEN 'MORNING'
        WHEN HOUR(ADS_SDATE) BETWEEN 12 AND 17 THEN 'AFTERNOON'
        ELSE 'EVENING' END AS "START_TIME"
FROM IVE_DATA.RAW_DATA.IVE_LIST_RAW
WHERE
    ADS_SDATE <= ADS_EDATE
    AND ADS_SDATE >= '2024-07-27'
    AND ADS_CONTRACT_PRICE <> 0;